// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zoom.Models;

[Table("Meeting")]
public partial class Meeting
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string Topic { get; set; }

    public TimeSpan? StartTime { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    public TimeSpan? EndTime { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    public int? Duration { get; set; }

    public string Agenda { get; set; }

    public string StartUrl { get; set; }

    [Column("ZoomID")]
    public long? ZoomId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ZoomAccount { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Passcode { get; set; }
    public string JoinUrl { get; internal set; }
}